language: php

php:
  - 7.2
  - 7.3

matrix:
  fast_finish: true

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - tests/Data/travis/imagick-setup.sh
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit

notifications:
  slack:
    rooms:
      - secure: zAfz+ejSmvLa93qF4CWpUhUcHaFjSNsmlV36RHbRbruACgU/STK7kvSoHNhBei6CrVleTnAIaUS5dfpciaIbEGZDNz1XsNhTmcvABUJ4fPgcHvRb7VsMVfhkpDoIKRRjrERAhy6g1i0K6N6NAU5rlNakzl8j8ekCUhJ9RJHT3Ofcgh9Oa/YknrTryIzYzXf7b6X+neTtfGgebBdsNohHax14qIb8gfwtMmpwYa/JgK96X/9uwegD/cDmLQmSqpevetqvCaSvpLUd43PyafqCFs1vnxJrjD7al9dhrNSe+HSK0/9JCo1eE9094RWu+CpY9/y3V+1sR/8pNyNelAt24TtkWtwwrNE54vy5mXuApsuxGgKnm/NqpBOjT2C0kxUCzlFkkkeWD+zng0w8J0VaRnb5VyWJB82l5L3ay5H6malGRu3jFtv3rpn/4Xt6akUEVchOq0az6Pat32uDdnrqB/Aw4+sTorJVsRMv3W3OlPN2BtO1v95qDtxDuvJw8HN//lTX460z03VGKCO31jNN4faunU59z8XuIWvo5DRyyPdmj4sJq7P0I3a3YylM1ZDJWSg/npxUzepRQHb1nyimccRWo7MJPzIt+cTaQop94byjC/k4G71ItkBh58eJGytWZycfJXIruj+a0DKTF49+ZWDa6JGJ5hIPbBmsA4ZKnAU=

