<?php
/**
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

namespace yii\captcha;

/**
 * DriverInterface defines the common interface to be implemented by CAPTCHA rendering drivers.
 */
interface DriverInterface
{
    /**
     * Generates new CAPTCHA code.
     * @return string CAPTCHA code.
     */
    public function generateVerifyCode(): string;

    /**
     * Renders the CAPTCHA image.
     * @param string $code CAPTCHA code
     * @return string image binary source.
     */
    public function renderImage(string $code): string;

    /**
     * Returns image MIME type for the content generated by [[renderImage()]].
     * @return string image MIME type.
     */
    public function getImageMimeType(): string;
}
